language: node_js
node_js:
  -  "node"
script:
  -  gulp
install:
  -  npm install -g firebase-tools
  - npm install -g gulp
  - npm install # install package.json's things
after_success:
 - firebase deploy --token $FIREBASE_TOKEN
