language: node_js
node_js:
    - node
script:
    - gulp
install:
    - 'npm install -g firebase-tools'
    - 'npm install -g gulp'
    - 'npm install'
after_success:
    - 'firebase deploy --token $FIREBASE_TOKEN'
