language: node_js
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
node_js:
- node
script:
- npm run test
before_deploy:
- npm run build
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: "$GH_TOKEN"
    target-branch: master
    fqdn: www.virtual-ptu.com
    repo: Virtual-PTU/virtual-ptu.github.io
    local-dir: build
  - provider: firebase
    token: "$Firebase_CI_API_Key"
    message: "Deploy successful"
    local-dir: build